### ISSUE TITLE
How to set up buy and sell points

### ISSUE THREAD

**Issue by cryptodigger** [HaschekSolutions/cryptotrader#1]
Hello,

I saw your previous bots projects and thats how I found this one. I cloned everthing onto my Raspberry but I am now just wondering how to I set up buy and sell points? In the previous bot your wrote you mentioned that, in this one I am not able to locate that.

Thanks for your help!

**Comment by chrisiaut** [comment]
It wasn't available until yesterday. Check out bots/uptrendsurfer.php and bots/waverider.php

**Comment by ferra-andre** [comment]
Hi, is there a chance to tell the bot when to buy cryptocurrency? 
for example: if I want the bot to buy when BTC is 8000 USD and then resell how I can do?

thanks!
