### ISSUE TITLE
Nib and fip parameters

### ISSUE THREAD

**Issue by trainingday01** [HaschekSolutions/cryptotrader#10]
Hello!
I'm trying to figure out how the fip value works. I have bought 0.21189432 ETH for 228 € when it's price was 1074.30€. Is this the right command to run?

php bots/waverider.php -p ETH-EUR -bw 228 -g 10 -pv 5 -nib fip 1074.30

Thank you!

**Comment by chrisiaut** [comment]
yes exactly! check the value with the "-sim" parameter first (simulation)

**Comment by trainingday01** [comment]
Okay! Thank you! :D
