### ISSUE TITLE
2020 update to coinbase pro

### ISSUE THREAD

**Issue by dandb2** [HaschekSolutions/cryptotrader#20]
Thanks to all who have contributed to the update 2020 / Coinbase Pro. Very well done.

One question though:

The scripts run very well under macOS (php 7.3.11). They do however not run under Raspbian (php 7.3.19). The output is as follows:

WAVERIDER:
pi@raspberrypi:~/cryptotrader-master $ php bots/waverider.php -p ETH-EUR -bw 100 -g 10 -pv 5 -nib -sim
 =============
 SIMULATION MODE 
 ============
 [i] Trading ETH-EUR
 [i] Will buy 100 EUR in ETH
 [i] Will sell when ETH will gain 10%, meaning when it's worth 110 EUR
 [i] After selling I will wait for ETH to drop by 5% before re-buying

 ====== BOT STARTING ====== 

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/cryptotrader-master/coinbase-pro.php:198
Stack trace:
#0 /home/pi/cryptotrader-master/coinbase-pro.php(41): CoinbaseExchange->makeRequest('/products/ETH-E...')
#1 /home/pi/cryptotrader-master/bots/waverider.php(53): CoinbaseExchange->updatePrices('ETH-EUR')
#2 {main}
  thrown in /home/pi/cryptotrader-master/coinbase-pro.php on line 198

UPTRENDSURFER:
pi@raspberrypi:~/cryptotrader-master $ php bots/uptrendsurfer.php -p ETH-EUR -bw 150 -g 5 -nib -sim
 =============
 SIMULATION MODE 
 ============
 [i] Trading ETH-EUR
 [i] Will buy 150 EUR in ETH
 [i] Will sell when ETH will gain 5%, meaning when it's worth 157.5 EUR

 ====== BOT STARTING ====== 

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/cryptotrader-master/coinbase-pro.php:198
Stack trace:
#0 /home/pi/cryptotrader-master/coinbase-pro.php(41): CoinbaseExchange->makeRequest('/products/ETH-E...')
#1 /home/pi/cryptotrader-master/bots/uptrendsurfer.php(50): CoinbaseExchange->updatePrices('ETH-EUR')
#2 {main}
  thrown in /home/pi/cryptotrader-master/coinbase-pro.php on line 198

Can you please help?

**Comment by geek-at** [comment]
apt-get install php-curl

Should fix it

dandb2 <notifications@github.com> schrieb am Do., 27. Aug. 2020, 11:16:

**Comment by dandb2** [comment]
top, works. Thank you!

**Comment by ZeroFux78** [comment]
@geek-at  Thank you!
