### ISSUE TITLE
Waverider bot wont start

### ISSUE THREAD

**Issue by LuxStatera** [HaschekSolutions/cryptotrader#23]
I followed the installation commands then ran the command for the waverider bot and it looks like its starting but then fails and gives the error:

PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/cryptotrader/coinbase-pro.php:198
Stack trace:
#0 /home/pi/cryptotrader/coinbase-pro.php(41): CoinbaseExchange->makeRequest('/products/BTC-U...')
#1 /home/pi/cryptotrader/bots/waverider.php(53): CoinbaseExchange->updatePrices('BTC-USD')
#2 {main}
  thrown in /home/pi/cryptotrader/coinbase-pro.php on line 198

Thank you for creating cryptotrader! looks like fun!

**Comment by ZeroFux78** [comment]
@LuxStatera I'm also receiving this error.  How did you resolve it?

**Comment by tbrugnara** [comment]
I have same problem, how to resolve?
