### ISSUE TITLE
Call to undefined function curl_init()

### ISSUE THREAD

**Issue by lbzt** [HaschekSolutions/cryptotrader#4]
Hello,
i just tried to run command php /home/pi/cryptotrader/examples/account_info.php
but i get the following error :
PHP Fatal error:  Call to undefined function curl_init() in /home/pi/cryptotrader/gdax.php on line 197

Could you please help me?
Regards

**Comment by chrisiaut** [comment]
You need the php extension "curl" to be active.

On Windows: edit the php.ini and add ```extension=ext/php_curl.dll``` where the extensions are

On Linux (debian based) install php5-curl or php7-curl. If you can't find it use ```àpt-cache search php curl``` that should show you the right package to install

On all other systems also look into the php.ini and load the extensions php_curl

**Comment by lbzt** [comment]
Thanks i installed the extension and now it's working propely.
Regards
