### ISSUE TITLE
Web stat output ?

### ISSUE THREAD

**Issue by phenixtai** [HaschekSolutions/cryptotrader#5]
Is it possible to have webhook for notification or an web dashboard simple with a short log or a graph with profit or lose

**Comment by chrisiaut** [comment]
interesting thoughts with webhooks.. will think about an implementation

**Comment by phenixtai** [comment]
thanks you're the best !!!!!! 
thanks to all your work :-)

**Comment by phenixtai** [comment]
With your old bot phptrader, there was a webhook to a rocket.cht will do the job fine :-)

**Comment by phenixtai** [comment]
add ">log.txt" at the end of the command to have a log.txt file in your folder who can help to check the bot

**Comment by phenixtai** [comment]
cd cryptotrader; php bots/uptrendsurfer.php -p BTC-EUR -bw 100 -g 10 -pv 5 -sim >log.txt
