### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by dandb2** [HaschekSolutions/cryptotrader#6]
Hi Christian,

I am currently running the cryptotrader and I do really admire you for being able to put such nice little app in place.

I am, however, wondering whether you could help with the following: When I run the script, I receive the following error-messages: 

PHP Notice:  Undefined index: message in /home/pi/cryptotrader/gdax.php on line 230
PHP Notice:  Undefined property: gdax::$lowestask in /home/pi/cryptotrader/gdax.php on line 53
PHP Notice:  Undefined property: gdax::$highestbid in /home/pi/cryptotrader/gdax.php on line 55
PHP Notice:  Undefined index: message in /home/pi/cryptotrader/gdax.php on line 230

Can you help to resolve this?

The script runs on a RPi3 with php5.

Looking forward to hearing from you. Greetings to AUT.

Cheers,
Daniel

**Comment by phenixtai** [comment]
as the author correct the error do :
git pull
