### ISSUE TITLE
gdax.php line 53, 55 & 230 errors

### ISSUE THREAD

**Issue by Haldon** [HaschekSolutions/cryptotrader#7]
When starting bot:

PHP Notice:  Undefined index: message in /home/pi/cryptotrader-master/gdax.php on line 230
PHP Notice:  Undefined property: gdax::$lowestask in /home/pi/cryptotrader-master/gdax.php on line 53
PHP Notice:  Undefined property: gdax::$highestbid in /home/pi/cryptotrader-master/gdax.php on line 55

This errors keep coming up.

**Comment by phenixtai** [comment]
as the author correct the error do :
git pull
