### ISSUE TITLE
PHP Fatal error:  Call to undefined function curl_init()

### ISSUE THREAD

**Issue by phenixtai** [HaschekSolutions/cryptotrader#8]
====== BOT STARTING ======

PHP Fatal error:  Call to undefined function curl_init() in /home/ubuntu/cryptotrader/gdax.php on line 197
ubuntu@linuxpc:~/cryptotrader$ php bots/uptrendsurfer.php -p BTC-EUR -bw 50 -g 30 -pv 10 -sim
PHP Notice:  Undefined offset: 10 in /home/dorian/cryptotrader/gdax.php on line 255
PHP Notice:  Undefined offset: 10 in /home/dorian/cryptotrader/gdax.php on line 255
 =============
 SIMULATION MODE
 ============
 [i] Trading BTC-EUR
 [i] Will buy 50 EUR in BTC
 [i] Will sell when BTC will gain 30%, meaning when it's worth 65 EUR

 ====== BOT STARTING ======

PHP Fatal error:  Call to undefined function curl_init() in /home/ubuntu/cryptotrader/gdax.php on line 197

**Comment by chrisiaut** [comment]
see #4

**Comment by phenixtai** [comment]
====== BOT STARTING ======      Change: 0 EUR

PHP Notice:  Undefined index: message in /home/ubuntu/cryptotrader/gdax.php on line 230
PHP Notice:  Undefined property: gdax::$lowestask in /home/ubuntu/cryptotrader/gdax.php on line 53
PHP Notice:  Undefined property: gdax::$highestbid in /home/ubuntu/cryptotrader/gdax.php on line 55
PHP Notice:  Undefined index: message in /home/ubuntu/cryptotrader/gdax.php on line 230
 [i] 10 EUR currently is 0.0007192 BTC
PHP Notice:  Undefined index: nib in /home/ubuntu/cryptotrader/bots/uptrendsurfer.php on line 57
  [!] Buying 0.0007192 BTC!
PHP Notice:  Undefined index: message in /home/ubuntu/cryptotrader/gdax.php on line 230
PHP Notice:  Undefined property: gdax::$lowestask in /home/ubuntu/cryptotrader/gdax.php on line 53
PHP Notice:  Undefined index: message in /home/ubuntu/cryptotrader/gdax.php on line 230 Current worth: 10.000476        Change: 0 EUR
-------------------------------------------------------------------------------------------------------------------

I have that after : apt-get install php5-curl but the bot seem work :-)

**Comment by phenixtai** [comment]
gdax.php line 53, 55 & 230 errors #7
 Closed	Haldon opened this issue 2 days ago · 0 comments

**Comment by phenixtai** [comment]
this message are just notice from php, 
the bot work even you see this message : 
PHP Notice: Undefined property ---> on line 53,55 and 230

**Comment by phenixtai** [comment]
as the author correct the error do :
git pull
